name: Build & deploy
on: push

jobs:
  build:
    name: Build pelican site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: py-actions/py-dependency-install@v4
      - name: Download theme
        uses: robinraju/release-downloader@v1
        with:
          repository: "tonyxty/pelican-lambda"
          latest: true
          fileName: pelican-lambda.zip
      - run: unzip pelican-lambda.zip
      - run: make publish
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
